let i=10;
console.log(i); //10
console.log(i++); //10
console.log(i); //11
console.log(++i); //12
console.log(i); //12
console.log(i--); //12
console.log(i); //11
console.log(--i); //10
console.log(i);  //10